### ISSUE TITLE
Supporting FCP and TTFB

### ISSUE THREAD

**Issue by bitttttten** [gtm-templates-simo-ahava/core-web-vitals#2]
The web-vitals package also supports [FCP and TTFB](https://github.com/GoogleChrome/web-vitals#functions) and it would be great to get these into GTM/Google Analytics. I see in the template it's not supported yet, and it doesn't look like I can edit the template or customise it myself.. although I could be missing something there.

So does the library plan to support these other functions? Perhaps as part of a configuration setting in the Tag Configuration panel?

**Comment by bitttttten** [comment]
I see it could be introduced as a template parameter, although I don't know where to customise it or configure it. Otherwise I would be opening a PR already 🙃

For example I see the "Namespace Objects" configuration option, inside the template although I don't see it here:

<img width="951" alt="Screenshot 2021-05-26 at 10 39 19" src="https://user-images.githubusercontent.com/19930241/119630180-fd189b80-be0e-11eb-967b-2806410060fb.png">

**Comment by sahava** [comment]
Fixed here: 87251ca43e4fb664a051c8f447f78549dba63c86

Also added INP
